from datetime import datetime
from types import TracebackType
from typing import TYPE_CHECKING, Protocol, Self
from uuid import UUID

from backend.app.audit.entities import AuditEvent
from backend.app.cases.entities import FraudCase
from backend.app.console.contracts import ConsoleRepository
from backend.app.evaluation.contracts import EvaluationRecord, ReviewFeedback
from backend.app.feedback.entities import AnalystDecision
from backend.app.fraud.ports import ModelVersion
from backend.app.profile.entities import Customer, CustomerBehaviorProfile, ProfileSnapshot
from backend.app.risk.entities import RiskAssessment
from backend.app.rules.contracts import RuleVersion
from backend.app.shared.events import DomainEvent, OutboxEvent
from backend.app.transaction.entities import Transaction
from backend.app.transaction.idempotency import IdempotencyRecord

if TYPE_CHECKING:
    from backend.app.profile.learning import LearningDecision


class CustomerRepository(Protocol):
    def get(self, customer_id: UUID) -> Customer | None: ...
    def add(self, customer: Customer) -> None: ...


class SnapshotRepository(Protocol):
    def get(self, snapshot_id: UUID) -> ProfileSnapshot | None: ...
    def add(self, snapshot: ProfileSnapshot) -> None: ...


class ModelRepository(Protocol):
    def get(self, version: str) -> ModelVersion | None: ...
    def add(self, model: ModelVersion) -> None: ...


class RuleRepository(Protocol):
    def get(self, version: str) -> RuleVersion | None: ...
    def add(self, rule: RuleVersion) -> None: ...


class AssessmentRepository(Protocol):
    def get(self, assessment_id: UUID) -> RiskAssessment | None: ...
    def add(self, assessment: RiskAssessment) -> None: ...


class FeedbackRepository(Protocol):
    def get(self, decision_id: UUID) -> AnalystDecision | None: ...
    def add(self, decision: AnalystDecision) -> None: ...


class AuditRepository(Protocol):
    def get(self, audit_id: UUID) -> AuditEvent | None: ...
    def add(self, event: AuditEvent) -> None: ...


class IdempotencyRepository(Protocol):
    def get(self, principal_id: UUID, key: str) -> IdempotencyRecord | None: ...
    def acquire(
        self, principal_id: UUID, key: str, request_sha256: str
    ) -> IdempotencyRecord | None: ...
    def add(self, record: IdempotencyRecord) -> None: ...


class TransactionRepository(Protocol):
    def get(self, transaction_id: UUID) -> Transaction | None: ...
    def add(self, transaction: Transaction) -> None: ...
    def history_before(
        self,
        customer_id: UUID,
        currency: str,
        *,
        since: datetime,
        before: datetime,
        exclude_transaction_id: UUID,
        limit: int,
    ) -> tuple[Transaction, ...]: ...


class CustomerProfileRepository(Protocol):
    def get(self, customer_id: UUID, currency: str) -> CustomerBehaviorProfile | None: ...
    def get_for_update(
        self, customer_id: UUID, currency: str
    ) -> CustomerBehaviorProfile | None: ...
    def get_revision(
        self,
        customer_id: UUID,
        currency: str,
        *,
        version: int | None = None,
    ) -> CustomerBehaviorProfile | None: ...
    def save(self, profile: CustomerBehaviorProfile, *, expected_version: int) -> None: ...


class FraudCaseRepository(Protocol):
    def get(self, case_id: UUID) -> FraudCase | None: ...
    def save(self, case: FraudCase) -> None: ...


class OutboxRepository(Protocol):
    def add(self, event: DomainEvent) -> None: ...
    def get(self, event_id: UUID) -> OutboxEvent | None: ...
    def pending(self, *, limit: int = 100) -> tuple[OutboxEvent, ...]: ...
    def record_attempt(self, event_id: UUID) -> None: ...
    def mark_published(self, event_id: UUID, at: datetime) -> None: ...


class EvaluationRepository(Protocol):
    def get(self, evaluation_id: UUID) -> EvaluationRecord | None: ...
    def add(self, record: EvaluationRecord) -> None: ...


class EvaluationReviewRepository(Protocol):
    def get(self, case_id: UUID, *, lock: bool = False) -> FraudCase | None: ...
    def find(self, evaluation_id: UUID) -> FraudCase | None: ...
    def save(self, case: FraudCase) -> None: ...
    def feedback(self, case_id: UUID) -> tuple[ReviewFeedback, ...]: ...
    def add_feedback(self, feedback: ReviewFeedback) -> None: ...


class ProfileLearningRepository(Protocol):
    def get(self, decision_id: UUID) -> "LearningDecision | None": ...
    def add(self, decision: "LearningDecision") -> None: ...


class UnitOfWork(Protocol):
    """Adapters must atomically commit business writes and outbox records."""

    @property
    def evaluations(self) -> EvaluationRepository: ...
    @property
    def reviews(self) -> EvaluationReviewRepository: ...
    @property
    def learning(self) -> ProfileLearningRepository: ...
    @property
    def customers(self) -> CustomerRepository: ...
    @property
    def transactions(self) -> TransactionRepository: ...
    @property
    def profiles(self) -> CustomerProfileRepository: ...
    @property
    def snapshots(self) -> SnapshotRepository: ...
    @property
    def models(self) -> ModelRepository: ...
    @property
    def rules(self) -> RuleRepository: ...
    @property
    def assessments(self) -> AssessmentRepository: ...
    @property
    def cases(self) -> FraudCaseRepository: ...
    @property
    def feedback(self) -> FeedbackRepository: ...
    @property
    def audit(self) -> AuditRepository: ...
    @property
    def outbox(self) -> OutboxRepository: ...
    @property
    def idempotency(self) -> IdempotencyRepository: ...

    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    @property
    def console(self) -> ConsoleRepository: ...
