"""business persistence"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0002_persistence"
down_revision = "0001_foundation"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("audit_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("detail", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("audit_id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        op.f("ix_audit_events_correlation_id"), "audit_events", ["correlation_id"], unique=False
    )
    op.create_index(op.f("ix_audit_events_entity_id"), "audit_events", ["entity_id"], unique=False)
    op.create_table(
        "customers",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("customer_id", name=op.f("pk_customers")),
    )
    op.create_table(
        "model_versions",
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("feature_version", sa.String(length=100), nullable=False),
        sa.Column("trained_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("artifact_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "artifact_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_model_versions_digest")
        ),
        sa.CheckConstraint(
            "status IN ('CANDIDATE','PRODUCTION','ARCHIVED')", name=op.f("ck_model_versions_status")
        ),
        sa.PrimaryKeyConstraint("version", name=op.f("pk_model_versions")),
        sa.UniqueConstraint("version", "feature_version", name=op.f("uq_model_versions_version")),
    )
    op.create_index(
        "uq_one_production_model",
        "model_versions",
        ["status"],
        unique=True,
        postgresql_where=sa.text("status = 'PRODUCTION'"),
    )
    op.create_table(
        "outbox_events",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "attempts >= 0 AND schema_version > 0", name=op.f("ck_outbox_events_versions")
        ),
        sa.CheckConstraint(
            "published_at IS NULL OR published_at >= occurred_at",
            name=op.f("ck_outbox_events_publication"),
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_outbox_events")),
    )
    op.create_index(
        "ix_outbox_pending",
        "outbox_events",
        ["occurred_at"],
        unique=False,
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.create_table(
        "rule_versions",
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("version", name=op.f("pk_rule_versions")),
    )
    op.create_table(
        "profile_snapshots",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("profile", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
            name=op.f("fk_profile_snapshots_customer_id_customers"),
        ),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("pk_profile_snapshots")),
        sa.UniqueConstraint("assessment_id", name=op.f("uq_profile_snapshots_assessment_id")),
        sa.UniqueConstraint(
            "snapshot_id",
            "assessment_id",
            "customer_id",
            "currency",
            name=op.f("uq_profile_snapshots_snapshot_id"),
        ),
    )
    op.create_table(
        "profiles",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("long_window_days", sa.Integer(), nullable=False),
        sa.Column("short_window_days", sa.Integer(), nullable=False),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f("ck_profiles_currency")),
        sa.CheckConstraint(
            "short_window_days > 0 AND long_window_days >= short_window_days",
            name=op.f("ck_profiles_windows"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_profiles_version")),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
            name=op.f("fk_profiles_customer_id_customers"),
        ),
        sa.PrimaryKeyConstraint("customer_id", "currency", name=op.f("pk_profiles")),
    )
    op.create_table(
        "transactions",
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("device_id", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "amount > 0 AND amount < 'Infinity'::numeric",
            name=op.f("ck_transactions_amount_positive"),
        ),
        sa.CheckConstraint(
            "channel IN ('MOBILE','WEB','ATM','BRANCH')", name=op.f("ck_transactions_channel")
        ),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f("ck_transactions_currency")),
        sa.CheckConstraint(
            "status IN ('RECEIVED','EVALUATED')", name=op.f("ck_transactions_status")
        ),
        sa.CheckConstraint("length(trim(device_id)) > 0", name=op.f("ck_transactions_device")),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
            name=op.f("fk_transactions_customer_id_customers"),
        ),
        sa.PrimaryKeyConstraint("transaction_id", name=op.f("pk_transactions")),
        sa.UniqueConstraint(
            "transaction_id", "customer_id", "currency", name=op.f("uq_transactions_transaction_id")
        ),
    )
    op.create_index(
        "ix_transactions_customer_time", "transactions", ["customer_id", "timestamp"], unique=False
    )
    op.create_table(
        "idempotency_records",
        sa.Column("principal_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("request_sha256", sa.String(length=64), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("response_json", sa.String(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "request_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_idempotency_records_digest")
        ),
        sa.CheckConstraint(
            "length(key) > 0 AND key = trim(key)", name=op.f("ck_idempotency_records_key")
        ),
        sa.CheckConstraint(
            "status_code >= 200 AND status_code < 300", name=op.f("ck_idempotency_records_status")
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.transaction_id"],
            name=op.f("fk_idempotency_records_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("principal_id", "key", name=op.f("pk_idempotency_records")),
    )
    op.create_table(
        "profile_observations",
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("admitted_version", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "admitted_version > 0 AND ordinal >= 0", name=op.f("ck_profile_observations_position")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id", "currency"],
            ["profiles.customer_id", "profiles.currency"],
            name=op.f("fk_profile_observations_customer_id_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id", "customer_id", "currency"],
            ["transactions.transaction_id", "transactions.customer_id", "transactions.currency"],
            name=op.f("fk_profile_observations_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("transaction_id", name=op.f("pk_profile_observations")),
        sa.UniqueConstraint(
            "customer_id", "currency", "ordinal", name=op.f("uq_profile_observations_customer_id")
        ),
    )
    op.create_table(
        "risk_assessments",
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("profile_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("feature_version", sa.String(length=100), nullable=False),
        sa.Column("rule_version", sa.String(length=100), nullable=False),
        sa.Column("policy_version", sa.String(length=100), nullable=False),
        sa.Column("strategy", sa.String(length=100), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(level, action) IN (('LOW','ALLOW'), ('MEDIUM','STEP_UP_VERIFICATION'), "
            "('HIGH','HOLD_AND_REVIEW'), ('CRITICAL','URGENT_REVIEW'))",
            name=op.f("ck_risk_assessments_decision"),
        ),
        sa.CheckConstraint("score >= 0 AND score <= 1", name=op.f("ck_risk_assessments_score")),
        sa.ForeignKeyConstraint(
            ["model_version", "feature_version"],
            ["model_versions.version", "model_versions.feature_version"],
            name=op.f("fk_risk_assessments_model_version_model_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_snapshot_id", "assessment_id", "customer_id", "currency"],
            [
                "profile_snapshots.snapshot_id",
                "profile_snapshots.assessment_id",
                "profile_snapshots.customer_id",
                "profile_snapshots.currency",
            ],
            name=op.f("fk_risk_assessments_profile_snapshot_id_profile_snapshots"),
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["rule_version"],
            ["rule_versions.version"],
            name=op.f("fk_risk_assessments_rule_version_rule_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id", "customer_id", "currency"],
            ["transactions.transaction_id", "transactions.customer_id", "transactions.currency"],
            name=op.f("fk_risk_assessments_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("assessment_id", name=op.f("pk_risk_assessments")),
        sa.UniqueConstraint(
            "assessment_id",
            "transaction_id",
            "model_version",
            name="uq_assessment_transaction_model",
        ),
        sa.UniqueConstraint("assessment_id", "transaction_id", name="uq_assessment_transaction"),
    )
    op.create_index(
        "ix_assessments_transaction", "risk_assessments", ["transaction_id"], unique=False
    )
    op.create_table(
        "analyst_decisions",
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("analyst_id", sa.Uuid(), nullable=False),
        sa.Column("verdict", sa.String(length=30), nullable=False),
        sa.Column("model_prediction", sa.Float(), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("comment", sa.String(), nullable=False),
        sa.CheckConstraint(
            "verdict IN ('CONFIRMED_FRAUD','LEGITIMATE','NEEDS_INVESTIGATION')",
            name=op.f("ck_analyst_decisions_verdict"),
        ),
        sa.CheckConstraint("length(trim(comment)) > 0", name=op.f("ck_analyst_decisions_comment")),
        sa.CheckConstraint(
            "model_prediction >= 0 AND model_prediction <= 1",
            name=op.f("ck_analyst_decisions_prediction"),
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id", "transaction_id", "model_version"],
            [
                "risk_assessments.assessment_id",
                "risk_assessments.transaction_id",
                "risk_assessments.model_version",
            ],
            name=op.f("fk_analyst_decisions_assessment_id_risk_assessments"),
        ),
        sa.PrimaryKeyConstraint("decision_id", name=op.f("pk_analyst_decisions")),
    )
    op.create_table(
        "fraud_cases",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id", "transaction_id"],
            ["risk_assessments.assessment_id", "risk_assessments.transaction_id"],
            name=op.f("fk_fraud_cases_assessment_id_risk_assessments"),
        ),
        sa.PrimaryKeyConstraint("case_id", name=op.f("pk_fraud_cases")),
        sa.UniqueConstraint("assessment_id", name=op.f("uq_fraud_cases_assessment_id")),
    )
    op.create_table(
        "case_transitions",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("previous", sa.String(length=30), nullable=False),
        sa.Column("target", sa.String(length=30), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_case_transitions_sequence")),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["fraud_cases.case_id"],
            name=op.f("fk_case_transitions_case_id_fraud_cases"),
        ),
        sa.PrimaryKeyConstraint("case_id", "sequence", name=op.f("pk_case_transitions")),
    )
    op.create_foreign_key(
        "fk_snapshot_assessment",
        "profile_snapshots",
        "risk_assessments",
        ["assessment_id"],
        ["assessment_id"],
        deferrable=True,
        initially="DEFERRED",
    )


def downgrade() -> None:
    op.drop_constraint("fk_snapshot_assessment", "profile_snapshots", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("case_transitions")
    op.drop_table("fraud_cases")
    op.drop_table("analyst_decisions")
    op.drop_index("ix_assessments_transaction", table_name="risk_assessments")
    op.drop_table("risk_assessments")
    op.drop_table("profile_observations")
    op.drop_table("idempotency_records")
    op.drop_index("ix_transactions_customer_time", table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("profiles")
    op.drop_table("profile_snapshots")
    op.drop_table("rule_versions")
    op.drop_index(
        "ix_outbox_pending",
        table_name="outbox_events",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_table("outbox_events")
    op.drop_index(
        "uq_one_production_model",
        table_name="model_versions",
        postgresql_where=sa.text("status = 'PRODUCTION'"),
    )
    op.drop_table("model_versions")
    op.drop_table("customers")
    op.drop_index(op.f("ix_audit_events_entity_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_correlation_id"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
